notas = [4, 10, 8, 7]
print(notas)
notas_2 = [5, 6, 9]
notas.append(3)
print(notas)
notas.extend(notas_2)
print(notas)
notas.insert(1, 1)
print(notas)
notas.append(10)
print(notas)
notas.pop()
notas.append(2)
print(notas)
media = sum(notas) / len(notas)
print(f"A média é {media}")
maior_nota = max(notas)
print(f"A maior nota foi {maior_nota}")
print(f"A nota mais baixa foi {min(notas)}")